# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

forward_create_tables = """
    CREATE TABLE compute_server (
        address test DEFAULT unknown NOT NULL
    )
    -- compute_server constraints
    ALTER TABLE ONLY compute_server
    ADD CONSTRAINT compute_server_pkey PRIMARY KEY (id);

    -- Create history tables
    SELECT create_history_table('compute_server'::regclass, 'edition_time', 'txid');
"""

backward_create_tables = """
    SELECT disable_history_tracking_for_table('compute_server'::regclass,
        get_history_table_name('compute_server'::regclass));
    SELECT drop_history_table('compute_server'::regclass);

    DROP TABLE point CASCADE;
"""


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catmaid", "0044_wrap_skeleton_summary_update_in_function"),
    ]

    operations = [
        migrations.RunSQL(
            forward_create_tables,
            backward_create_tables,
            [
                migrations.CreateModel(
                    name="compute_server",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "creation_time",
                            models.DateTimeField(default=django.utils.timezone.now),
                        ),
                        (
                            "edition_time",
                            models.DateTimeField(default=django.utils.timezone.now),
                        ),
                        ("address", models.TextField(default="unknown")),
                        (
                            "editor",
                            models.ForeignKey(
                                db_column="editor_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="point_editor",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "project",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="catmaid.Project",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={"db_table": "compute_server"},
                )
            ],
        )
    ]
